#!/usr/bin/env bash

set -e

hzVersion=${1:-$(hazelcastVersion)}

cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

ec2Type="m6g.xlarge"
aws-create --count 3 --instanceType ${ec2Type} --outputFile a.box
aws-create --count 3 --instanceType ${ec2Type} --outputFile b.box
aws-create --count 3 --instanceType ${ec2Type} --outputFile c.box

ops="${ops} -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
ops="${ops} -Dhazelcast.enterprise.wanrep.batch.size=150"

mOps="${mOps} -Dhazelcast.connection.monitor.interval=1000 -Dhazelcast.connection.monitor.max.faults=30 -Dhazelcast.rest.enabled=true"

hz memberOps "-Xms4G -Xmx4G ${ops} ${mOps}"
hz clientOps "-Xms400M -Xmx400M ${ops}"

hz cluster -id A -size M3C2 -v ${hzVersion} -ee -boxes a.box
hz cluster -id B -size M3C2 -v ${hzVersion} -ee -boxes b.box
hz cluster -id C -size M3C2 -v ${hzVersion} -ee -boxes c.box

echo 'WAN Active Active'
hz wan A B C
hz wan B C A
hz wan C A B

hz driver Client1
hz run -id '(A|B|C)' put &

hz driver Client2
hz run -id '(A|B|C)' get &

hz run validate

until hz run clusterSafe; do
    sleep 10
done
hz run validate

hz run -id A put &
hz run -id '(B|C)' get &
wait

hz run -id A clusterShutdown
hz embeddedRestart -id A Member

pubIp=$(hz ip -id A Member1);
for i in {0..8} ; do
    for group in B C ${hzVersion} ; do
        curl -H "Content-type: text/plain" -X POST -d "wanReplication&${group}&mapBak1HD${i}" --URL http://${pubIp}:5701/hazelcast/rest/wan/sync/map
    done
done


