#!/usr/bin/env bash

cleanup() {
    exitCode=$?
    hz download
    hz chart metrics
    exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

# TODO
#Start clusters in different zones

set -e

hzVersion=${1:-$(hazelcastVersion)}

#us-west-1	US West (N. California):ami-02e51256b01eaa9ef subnet-0db700125fd2a4cc1 vpc-b5efd4d1
#US East (N. Virginia) us-east-1:ami-05d1de0f40492c232
#Texas is Ohio (us-east-2): ami-093cbcaab778edd5e subnet-0467850a244253773 vpc-0e686372589fd40c8
aws-create --count 3 --region us-west-1 --imageId ami-02e51256b01eaa9ef --subnetId subnet-0db700125fd2a4cc1 --outputFile a.box
aws-create --count 3 --outputFile b.box
aws-create --count 3 --region us-east-2 --imageId ami-093cbcaab778edd5e --subnetId subnet-0467850a244253773 --outputFile c.box

ops="${ops} -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
ops="${ops} -Dhazelcast.enterprise.wanrep.batch.size=150"

mOps="${mOps} -Dhazelcast.connection.monitor.interval=1000 -Dhazelcast.connection.monitor.max.faults=30"
mOps="${mOps} -Dhz.network.rest-api.enabled=true -Dhz.network.rest-api.endpoint-groups.wan.enabled=true"

hz memberOps "-Xms4G -Xmx4G ${ops} ${mOps}"
hz clientOps "-Xms400M -Xmx400M ${ops}"

hz cluster -id A -size M3C2 -v ${hzVersion} -ee -boxes a.box
hz cluster -id B -size M3C2 -v ${hzVersion} -ee -boxes b.box
hz cluster -id C -size M3C2 -v ${hzVersion} -ee -boxes c.box

echo 'WAN Active Active'
hz wan A B C
hz wan B C A
hz wan C A B

#for the new wan configuration to take effect the cluster must be bounced
# "restarted" and the new xml config will be used
hz bounce Member

until hz run untilClusterSafe; do
    sleep 10
done

hz driver Client1
for clusterID in A B C; do
  #  change prefix in file
  hz task preFixPut put_mapBak1HD prefix ${clusterID}
  #  async run preFixPut
  hz submit -id ${clusterID} preFixPut
done

hz driver Client2
hz run -id '(A|B|C)' get &

echo "Sleeping 300 seconds"
sleep 300

#pubIp=$(hz ip -id A Member1);
#for group in B C ${hzVersion} ; do
#    curl -H "Content-type: text/plain" -X POST -d "wanReplication&${group}&mapBak1HD" --URL http://${pubIp}:5701/hazelcast/rest/wan/sync/map
#done
echo "Stopping test"

hz stop
wait

hz download

hz wipe
aws-terminate a.box b.box c.box

