#!/usr/bin/env bash

cleanup() {
  exitCode=$?
  hz download
  hz chart metrics
  exit ${exitCode}
}
trap "cleanup" INT TERM EXIT

set -e

defaultHazelcastVersion=5.0

hzVersion=${1:-$(defaultHazelcastVersion)}

#us-west-1	US West (N. California):ami-02e51256b01eaa9ef subnet-9fa278c6 vpc-b5efd4d1
#US East (N. Virginia) us-east-1:ami-05d1de0f40492c232
#Texas is Ohio (us-east-2): ami-093cbcaab778edd5e subnet-0467850a244253773 vpc-0e686372589fd40c8
aws-create --count 5 --region us-west-1 --imageId ami-02e51256b01eaa9ef --subnetId subnet-9fa278c6 --key jenkins-ec2-key --outputFile a.box
aws-create --count 5 --region us-east-1 --outputFile b.box
aws-create --count 5 --region us-east-2 --imageId ami-093cbcaab778edd5e --subnetId subnet-0467850a244253773 --key jenkins-ec2-key-east-2 --outputFile c.box

ops="${ops} -Dhazelcast.enterprise.license.key=${HAZELCAST_EE_KEY} -Dhazelcast.backpressure.enabled=true"
ops="${ops} -Dhazelcast.enterprise.wanrep.batch.size=150"

mOps="${mOps} -Dhazelcast.connection.monitor.interval=1000 -Dhazelcast.connection.monitor.max.faults=30"
mOps="${mOps} -Dhz.network.rest-api.enabled=true -Dhz.network.rest-api.endpoint-groups.wan.enabled=true"

hz memberOps "-Xms4G -Xmx4G ${ops} ${mOps}"
hz clientOps "-Xms400M -Xmx400M ${ops}"

hz cluster -id A -tag AA -size M3C2 -v ${hzVersion} -ee -boxes a.box
hz cluster -id B -tag BB -size M3C2 -v ${hzVersion} -ee -boxes b.box
hz cluster -id C -tag CC -size M3C2 -v ${hzVersion} -ee -boxes c.box

echo 'Configuring WAN Active Active'
hz wan A B C
hz wan B C A
hz wan C A B

#for the new wan configuration to take effect the cluster must be bounced
# "restarted" and the new xml config will be used
hz bounce Member

until hz run untilClusterSafe; do
  sleep 10
done

hz driver Client2
hz run -id '(A|B|C)' listenMergedMulti

hz driver Client1
for clusterID in A B C; do
  #  change prefix in file
  hz task prefixPut prefixPut prefix ${clusterID}
  #  async run preFixPut
  hz submit -id ${clusterID} prefixPut
done

#hz driver Client1
#hz run -id '(A|B|C)' prefixPut &

echo "Sleeping 20 seconds"
sleep 20


hz driver Member1
echo "Splitting all"
hz split AA BB CC
hz split BB CC AA
hz split CC AA BB
sleep 20

echo "Healing all"
hz heal

echo "Waiting 20 seconds after heal"
sleep 20


echo "Stopping test"
hz stop

# sync all maps
pubIpA=$(hz ip -id A Member1)
for group in B C; do
  curl -H "Content-type: text/plain" -X POST -d "A&IGNORE&wanReplication&${group}" --URL http://${pubIpA}:5701/hazelcast/rest/wan/sync/allmaps
  sleep 10
done

echo "Dumping maps"
hz driver Client2
hz run -id '(A|B|C)' dump

wait

hz download

hz wipe

aws-terminate -r us-west-1 a.box
aws-terminate -r us-east-1 b.box
aws-terminate -r us-east-2 c.box
